-- MASSIVE DATA INSERTION SCRIPT
-- Generated from parallel research data
-- Generated: 2025-12-06T18:35:29.675992
-- Total statements: 154

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2010 - Year in Review', 'اقتصاد اليمن 2010 - مراجعة السنة', 'The year 2010 served as a pre-crisis baseline for Yemen, characterized by robust economic growth and simmering political and humanitarian challenges. Economically, the country experienced a strong real GDP growth of 7.7%, primarily driven by the coming online of the Yemen LNG project and high oil prices, despite a high inflation rate of 11.2%. Politically, the year began with the formal end of the Sixth Sa''ada War against the Houthis in February, though the government continued to face a growing threat from Al-Qaeda in the Arabian Peninsula (AQAP) and underlying political instability. The humanitarian situation remained precarious, with 7.5 million people (32.1% of the population) classified as food insecure, and up to 300,000 internally displaced persons (IDPs) from the northern conflict requiring aid.', 'The year 2010 served as a pre-crisis baseline for Yemen, characterized by robust economic growth and simmering political and humanitarian challenges. Economically, the country experienced a strong real GDP growth of 7.7%, primarily driven by the coming online of the Yemen LNG project and high oil prices, despite a high inflation rate of 11.2%. Politically, the year began with the formal end of the Sixth Sa''ada War against the Houthis in February, though the government continued to face a growing threat from Al-Qaeda in the Arabian Peninsula (AQAP) and underlying political instability. The humanitarian situation remained precarious, with 7.5 million people (32.1% of the population) classified as food insecure, and up to 300,000 internally displaced persons (IDPs) from the northern conflict requiring aid.', '2010-12-31', 'economic', 'high', 'IMF Staff Report 2010, UN OCHA FTS, WFP, IRIN, FAO, FRED St. Louis', 'year-2010,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('End of 6th Sa''ada War (Feb 2010)', 'End of 6th Sa''ada War (Feb 2010)', 'End of 6th Sa''ada War (Feb 2010) led to Temporary reduction in internal conflict. pre-2011 stability', 'End of 6th Sa''ada War (Feb 2010) led to Temporary reduction in internal conflict. pre-2011 stability', '2010-06-30', 'political', 'medium', 'IMF Staff Report 2010, UN OCHA FTS, WFP, IRIN, FAO, FRED St. Louis', 'year-2010,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('High oil prices and LNG production coming online', 'High oil prices and LNG production coming online', 'High oil prices and LNG production coming online led to Real GDP growth of 7.7%. IMF 2010', 'High oil prices and LNG production coming online led to Real GDP growth of 7.7%. IMF 2010', '2010-06-30', 'political', 'medium', 'IMF Staff Report 2010, UN OCHA FTS, WFP, IRIN, FAO, FRED St. Louis', 'year-2010,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Global food and fuel price volatility', 'Global food and fuel price volatility', 'Global food and fuel price volatility led to Inflation rate of 11.2%. IMF 2010', 'Global food and fuel price volatility led to Inflation rate of 11.2%. IMF 2010', '2010-06-30', 'political', 'medium', 'IMF Staff Report 2010, UN OCHA FTS, WFP, IRIN, FAO, FRED St. Louis', 'year-2010,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('High population growth and limited resources', 'High population growth and limited resources', 'High population growth and limited resources led to 7.5M people food insecure. WFP 2010', 'High population growth and limited resources led to 7.5M people food insecure. WFP 2010', '2010-06-30', 'political', 'medium', 'IMF Staff Report 2010, UN OCHA FTS, WFP, IRIN, FAO, FRED St. Louis', 'year-2010,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2011 - Year in Review', 'اقتصاد اليمن 2011 - مراجعة السنة', 'The year 2011 was defined by the Yemeni Revolution, a wave of Arab Spring protests that led to widespread political turmoil and a severe economic contraction. The protests and associated conflict, including attacks on critical infrastructure like oil pipelines, caused a sharp decline in real GDP by 12.7% and fueled an inflation rate of 19.54%. The political crisis culminated in the signing of the Gulf Cooperation Council (GCC) Initiative in November, which established a framework for a political transition. Concurrently, the humanitarian situation deteriorated significantly, with 10.6 million people becoming food-insecure and tens of thousands displaced by fighting, particularly in the Abyan Governorate.', 'The year 2011 was defined by the Yemeni Revolution, a wave of Arab Spring protests that led to widespread political turmoil and a severe economic contraction. The protests and associated conflict, including attacks on critical infrastructure like oil pipelines, caused a sharp decline in real GDP by 12.7% and fueled an inflation rate of 19.54%. The political crisis culminated in the signing of the Gulf Cooperation Council (GCC) Initiative in November, which established a framework for a political transition. Concurrently, the humanitarian situation deteriorated significantly, with 10.6 million people becoming food-insecure and tens of thousands displaced by fighting, particularly in the Abyan Governorate.', '2011-12-31', 'economic', 'high', 'World Bank, IMF, Macrotrends, US Treasury, UN OCHA, ConstitutionNet, Sana''a Center, ReliefWeb, UN News, CS Monitor, Washington Post', 'year-2011,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemeni Revolution (Arab Spring)', 'Yemeni Revolution (Arab Spring)', 'Yemeni Revolution (Arab Spring) led to Real GDP Contraction. -12.7%', 'Yemeni Revolution (Arab Spring) led to Real GDP Contraction. -12.7%', '2011-06-30', 'political', 'medium', 'World Bank, IMF, Macrotrends, US Treasury, UN OCHA, ConstitutionNet, Sana''a Center, ReliefWeb, UN News, CS Monitor, Washington Post', 'year-2011,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Attacks on oil pipelines and electricity plants', 'Attacks on oil pipelines and electricity plants', 'Attacks on oil pipelines and electricity plants led to Oil production drop and fuel shortages. ', 'Attacks on oil pipelines and electricity plants led to Oil production drop and fuel shortages. ', '2011-06-30', 'political', 'medium', 'World Bank, IMF, Macrotrends, US Treasury, UN OCHA, ConstitutionNet, Sana''a Center, ReliefWeb, UN News, CS Monitor, Washington Post', 'year-2011,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Political turmoil and supply chain disruption', 'Political turmoil and supply chain disruption', 'Political turmoil and supply chain disruption led to Food price increase. +46%', 'Political turmoil and supply chain disruption led to Food price increase. +46%', '2011-06-30', 'political', 'medium', 'World Bank, IMF, Macrotrends, US Treasury, UN OCHA, ConstitutionNet, Sana''a Center, ReliefWeb, UN News, CS Monitor, Washington Post', 'year-2011,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Political instability and conflict in Abyan', 'Political instability and conflict in Abyan', 'Political instability and conflict in Abyan led to Internal Displacement. Tens of thousands', 'Political instability and conflict in Abyan led to Internal Displacement. Tens of thousands', '2011-06-30', 'political', 'medium', 'World Bank, IMF, Macrotrends, US Treasury, UN OCHA, ConstitutionNet, Sana''a Center, ReliefWeb, UN News, CS Monitor, Washington Post', 'year-2011,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2012 - Year in Review', 'اقتصاد اليمن 2012 - مراجعة السنة', 'The year 2012 marked the formal political transition in Yemen, with the unopposed election of Abdrabbuh Mansur Hadi as President in February, ending the 33-year rule of Ali Abdullah Saleh under the GCC Initiative. Economically, the country began a fragile recovery from the 2011 crisis, with real GDP growth estimated at 1.4%, though political and security upheaval continued to decelerate progress. The government faced a significant fiscal challenge, with the deficit reaching 9.4% of GDP, partly due to large petroleum subsidies. The humanitarian situation remained dire, with approximately 10 million people food insecure and 385,000 internally displaced persons, necessitating a UN Humanitarian Response Plan that was 55.7% funded.', 'The year 2012 marked the formal political transition in Yemen, with the unopposed election of Abdrabbuh Mansur Hadi as President in February, ending the 33-year rule of Ali Abdullah Saleh under the GCC Initiative. Economically, the country began a fragile recovery from the 2011 crisis, with real GDP growth estimated at 1.4%, though political and security upheaval continued to decelerate progress. The government faced a significant fiscal challenge, with the deficit reaching 9.4% of GDP, partly due to large petroleum subsidies. The humanitarian situation remained dire, with approximately 10 million people food insecure and 385,000 internally displaced persons, necessitating a UN Humanitarian Response Plan that was 55.7% funded.', '2012-12-31', 'economic', 'high', 'World Bank, International Monetary Fund (IMF), UN Office for the Coordination of Humanitarian Affairs (OCHA), Internal Displacement Monitoring Centre (IDMC), Macrotrends, PoundSterlingLive, FRED', 'year-2012,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('GCC Initiative and Presidential Election', 'GCC Initiative and Presidential Election', 'GCC Initiative and Presidential Election led to Formal end of Saleh''s 33-year rule. Political Transition', 'GCC Initiative and Presidential Election led to Formal end of Saleh''s 33-year rule. Political Transition', '2012-06-30', 'political', 'medium', 'World Bank, International Monetary Fund (IMF), UN Office for the Coordination of Humanitarian Affairs (OCHA), Internal Displacement Monitoring Centre (IDMC), Macrotrends, PoundSterlingLive, FRED', 'year-2012,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Continued security upheaval and conflict (e.g., Abyan)', 'Continued security upheaval and conflict (e.g., Abyan)', 'Continued security upheaval and conflict (e.g., Abyan) led to Deceleration of economic growth to 1.4%. World Bank 2012', 'Continued security upheaval and conflict (e.g., Abyan) led to Deceleration of economic growth to 1.4%. World Bank 2012', '2012-06-30', 'political', 'medium', 'World Bank, International Monetary Fund (IMF), UN Office for the Coordination of Humanitarian Affairs (OCHA), Internal Displacement Monitoring Centre (IDMC), Macrotrends, PoundSterlingLive, FRED', 'year-2012,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Post-revolution political instability and fiscal expansion', 'Post-revolution political instability and fiscal expansion', 'Post-revolution political instability and fiscal expansion led to High inflation. 9.89% - 20.4%) and large fiscal deficit (9.4% of GDP', 'Post-revolution political instability and fiscal expansion led to High inflation. 9.89% - 20.4%) and large fiscal deficit (9.4% of GDP', '2012-06-30', 'political', 'medium', 'World Bank, International Monetary Fund (IMF), UN Office for the Coordination of Humanitarian Affairs (OCHA), Internal Displacement Monitoring Centre (IDMC), Macrotrends, PoundSterlingLive, FRED', 'year-2012,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2014 - Year in Review', 'اقتصاد اليمن 2014 - مراجعة السنة', 'The year 2014 was defined by a rapid deterioration of Yemen''s political and security environment, culminating in the Houthi takeover of the capital, Sanaa, in September, which effectively marked the beginning of the current civil war. Economically, the country faced severe challenges, including a substantial decline in oil revenue due to the sabotage of oil facilities and the government''s controversial elimination of fuel subsidies under pressure from the IMF. This instability resulted in a real GDP contraction of -3.9% and contributed to a humanitarian crisis that saw 10.5 million people food insecure and over 334,000 internally displaced persons by the end of the year.', 'The year 2014 was defined by a rapid deterioration of Yemen''s political and security environment, culminating in the Houthi takeover of the capital, Sanaa, in September, which effectively marked the beginning of the current civil war. Economically, the country faced severe challenges, including a substantial decline in oil revenue due to the sabotage of oil facilities and the government''s controversial elimination of fuel subsidies under pressure from the IMF. This instability resulted in a real GDP contraction of -3.9% and contributed to a humanitarian crisis that saw 10.5 million people food insecure and over 334,000 internally displaced persons by the end of the year.', '2014-12-31', 'economic', 'high', 'IMF, World Bank, UN OCHA, Trading Economics, Index Mundi, Exchange Rates UK, Crisis Group', 'year-2014,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Sabotage of oil facilities', 'Sabotage of oil facilities', 'Sabotage of oil facilities led to Decline in oil revenue and fiscal deterioration. IMF 2014', 'Sabotage of oil facilities led to Decline in oil revenue and fiscal deterioration. IMF 2014', '2014-06-30', 'political', 'medium', 'IMF, World Bank, UN OCHA, Trading Economics, Index Mundi, Exchange Rates UK, Crisis Group', 'year-2014,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi takeover of Sanaa (Sep 2014)', 'Houthi takeover of Sanaa (Sep 2014)', 'Houthi takeover of Sanaa (Sep 2014) led to Escalation of political instability and start of civil war. UN/Crisis Group 2014', 'Houthi takeover of Sanaa (Sep 2014) led to Escalation of political instability and start of civil war. UN/Crisis Group 2014', '2014-06-30', 'political', 'medium', 'IMF, World Bank, UN OCHA, Trading Economics, Index Mundi, Exchange Rates UK, Crisis Group', 'year-2014,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Political instability and oil revenue decline', 'Political instability and oil revenue decline', 'Political instability and oil revenue decline led to Real GDP contraction of -3.9%. World Bank 2014', 'Political instability and oil revenue decline led to Real GDP contraction of -3.9%. World Bank 2014', '2014-06-30', 'political', 'medium', 'IMF, World Bank, UN OCHA, Trading Economics, Index Mundi, Exchange Rates UK, Crisis Group', 'year-2014,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('IMF/World Bank pressure', 'IMF/World Bank pressure', 'IMF/World Bank pressure led to Government elimination of fuel subsidies. IMF 2014', 'IMF/World Bank pressure led to Government elimination of fuel subsidies. IMF 2014', '2014-06-30', 'political', 'medium', 'IMF, World Bank, UN OCHA, Trading Economics, Index Mundi, Exchange Rates UK, Crisis Group', 'year-2014,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2015 - Year in Review', 'اقتصاد اليمن 2015 - مراجعة السنة', 'The year 2015 was defined by the escalation of the Yemeni Civil War, marked by the launch of the Saudi-led "Operation Decisive Storm" in March, which transitioned into "Operation Restoring Hope" in April. This military intervention led to a severe economic contraction, with the GDP plummeting by nearly 28%, and triggered a massive humanitarian crisis. The internationally recognized government of President Hadi was forced to operate from Aden, while the Houthis maintained control over the capital, Sanaa, leading to a de facto political and economic split. The conflict and subsequent blockade severely disrupted trade, oil production, and state finances, pushing millions into acute food insecurity and displacing over two million people.', 'The year 2015 was defined by the escalation of the Yemeni Civil War, marked by the launch of the Saudi-led "Operation Decisive Storm" in March, which transitioned into "Operation Restoring Hope" in April. This military intervention led to a severe economic contraction, with the GDP plummeting by nearly 28%, and triggered a massive humanitarian crisis. The internationally recognized government of President Hadi was forced to operate from Aden, while the Houthis maintained control over the capital, Sanaa, leading to a de facto political and economic split. The conflict and subsequent blockade severely disrupted trade, oil production, and state finances, pushing millions into acute food insecurity and displacing over two million people.', '2015-12-31', 'economic', 'high', 'Macrotrends, IndexMundi, Exchange-Rates.org, UN OCHA, World Bank, IMF, Wikipedia, Britannica, Council on Foreign Relations, IOM', 'year-2015,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Operation Decisive Storm (March 2015)', 'Operation Decisive Storm (March 2015)', 'Operation Decisive Storm (March 2015) led to GDP collapse. -27.99% growth', 'Operation Decisive Storm (March 2015) led to GDP collapse. -27.99% growth', '2015-06-30', 'political', 'medium', 'Macrotrends, IndexMundi, Exchange-Rates.org, UN OCHA, World Bank, IMF, Wikipedia, Britannica, Council on Foreign Relations, IOM', 'year-2015,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Saudi-led coalition blockade and conflict', 'Saudi-led coalition blockade and conflict', 'Saudi-led coalition blockade and conflict led to Humanitarian crisis. 10.6M food insecure, 2.5M IDPs', 'Saudi-led coalition blockade and conflict led to Humanitarian crisis. 10.6M food insecure, 2.5M IDPs', '2015-06-30', 'political', 'medium', 'Macrotrends, IndexMundi, Exchange-Rates.org, UN OCHA, World Bank, IMF, Wikipedia, Britannica, Council on Foreign Relations, IOM', 'year-2015,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Collapse of oil production and government revenue', 'Collapse of oil production and government revenue', 'Collapse of oil production and government revenue led to Fiscal crisis and currency depreciation. 215.07 YER/USD average', 'Collapse of oil production and government revenue led to Fiscal crisis and currency depreciation. 215.07 YER/USD average', '2015-06-30', 'political', 'medium', 'Macrotrends, IndexMundi, Exchange-Rates.org, UN OCHA, World Bank, IMF, Wikipedia, Britannica, Council on Foreign Relations, IOM', 'year-2015,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2016 - Year in Review', 'اقتصاد اليمن 2016 - مراجعة السنة', 'The year 2016 was defined by the catastrophic **split of the Central Bank of Yemen (CBY)** in September, when the internationally recognized government relocated its headquarters from Sana''a to Aden, effectively fragmenting the country''s financial system. This move immediately triggered a severe liquidity crisis and the cessation of civil servant salary payments in Houthi-controlled areas, deepening the economic war. The conflict and financial collapse led to a **real GDP contraction of -9.38%** and an annual inflation rate of 21.30%. The humanitarian crisis intensified, with **14.4 million people facing food insecurity**, underscoring the direct link between the political conflict and the economic and humanitarian catastrophe.', 'The year 2016 was defined by the catastrophic **split of the Central Bank of Yemen (CBY)** in September, when the internationally recognized government relocated its headquarters from Sana''a to Aden, effectively fragmenting the country''s financial system. This move immediately triggered a severe liquidity crisis and the cessation of civil servant salary payments in Houthi-controlled areas, deepening the economic war. The conflict and financial collapse led to a **real GDP contraction of -9.38%** and an annual inflation rate of 21.30%. The humanitarian crisis intensified, with **14.4 million people facing food insecurity**, underscoring the direct link between the political conflict and the economic and humanitarian catastrophe.', '2016-12-31', 'economic', 'high', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('CBY relocation to Aden (Sep 2016)', 'CBY relocation to Aden (Sep 2016)', 'CBY relocation to Aden (Sep 2016) led to Banking crisis and liquidity shortage. quantified impact: 14.1M people in need of assistance', 'CBY relocation to Aden (Sep 2016) led to Banking crisis and liquidity shortage. quantified impact: 14.1M people in need of assistance', '2016-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('CBY relocation to Aden (Sep 2016)', 'CBY relocation to Aden (Sep 2016)', 'CBY relocation to Aden (Sep 2016) led to Cessation of civil servant salary payments in Sana''a. quantified impact: millions of unpaid salaries', 'CBY relocation to Aden (Sep 2016) led to Cessation of civil servant salary payments in Sana''a. quantified impact: millions of unpaid salaries', '2016-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict escalation and CBY split', 'Conflict escalation and CBY split', 'Conflict escalation and CBY split led to Real GDP contraction. quantified impact: -9.38% growth', 'Conflict escalation and CBY split led to Real GDP contraction. quantified impact: -9.38% growth', '2016-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Cessation of CBY foreign exchange support', 'Cessation of CBY foreign exchange support', 'Cessation of CBY foreign exchange support led to YER depreciation. quantified impact: Official rate adjusted to 250 YER/USD', 'Cessation of CBY foreign exchange support led to YER depreciation. quantified impact: Official rate adjusted to 250 YER/USD', '2016-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict and economic collapse', 'Conflict and economic collapse', 'Conflict and economic collapse led to Increased food insecurity. quantified impact: 14.4M food insecure', 'Conflict and economic collapse led to Increased food insecurity. quantified impact: 14.4M food insecure', '2016-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, CEIC Data, Macrotrends, Al Jazeera, Sana''a Center for Strategic Studies, ReliefWeb', 'year-2016,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2017 - Year in Review', 'اقتصاد اليمن 2017 - مراجعة السنة', 'The year 2017 was defined by a severe escalation of the humanitarian crisis, primarily driven by the Saudi-led coalition''s total blockade in November and the world''s largest recorded cholera outbreak, which surpassed one million suspected cases. Economically, the country saw a continued contraction of real GDP by an estimated 5.9%, coupled with a sharp rise in inflation to 24.5%. The ongoing conflict and the split of the Central Bank of Yemen led to a significant divergence between the official (250 YER/USD) and parallel exchange rates, further crippling the economy and exacerbating food insecurity for 17 million people. The blockade severely restricted the flow of essential goods, pushing the country closer to famine.', 'The year 2017 was defined by a severe escalation of the humanitarian crisis, primarily driven by the Saudi-led coalition''s total blockade in November and the world''s largest recorded cholera outbreak, which surpassed one million suspected cases. Economically, the country saw a continued contraction of real GDP by an estimated 5.9%, coupled with a sharp rise in inflation to 24.5%. The ongoing conflict and the split of the Central Bank of Yemen led to a significant divergence between the official (250 YER/USD) and parallel exchange rates, further crippling the economy and exacerbating food insecurity for 17 million people. The blockade severely restricted the flow of essential goods, pushing the country closer to famine.', '2017-12-31', 'economic', 'high', 'World Bank, IMF, UN OCHA FTS, IOM TFPM, OpenDataForAfrica, The Global Economy, ReliefWeb, CNN', 'year-2017,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Saudi-led Coalition Blockade (Nov 2017)', 'Saudi-led Coalition Blockade (Nov 2017)', 'Saudi-led Coalition Blockade (Nov 2017) led to Exacerbated humanitarian crisis and food insecurity. 17M people', 'Saudi-led Coalition Blockade (Nov 2017) led to Exacerbated humanitarian crisis and food insecurity. 17M people', '2017-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA FTS, IOM TFPM, OpenDataForAfrica, The Global Economy, ReliefWeb, CNN', 'year-2017,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict and Collapse of Public Services', 'Conflict and Collapse of Public Services', 'Conflict and Collapse of Public Services led to World''s largest recorded cholera outbreak. 1M+ suspected cases', 'Conflict and Collapse of Public Services led to World''s largest recorded cholera outbreak. 1M+ suspected cases', '2017-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA FTS, IOM TFPM, OpenDataForAfrica, The Global Economy, ReliefWeb, CNN', 'year-2017,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict and Central Bank Split', 'Conflict and Central Bank Split', 'Conflict and Central Bank Split led to Real GDP contraction. -5.9%', 'Conflict and Central Bank Split led to Real GDP contraction. -5.9%', '2017-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA FTS, IOM TFPM, OpenDataForAfrica, The Global Economy, ReliefWeb, CNN', 'year-2017,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Central Bank Split and War Financing', 'Central Bank Split and War Financing', 'Central Bank Split and War Financing led to Parallel market currency depreciation. 250 → 360 YER/USD', 'Central Bank Split and War Financing led to Parallel market currency depreciation. 250 → 360 YER/USD', '2017-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA FTS, IOM TFPM, OpenDataForAfrica, The Global Economy, ReliefWeb, CNN', 'year-2017,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2018 - Year in Review', 'اقتصاد اليمن 2018 - مراجعة السنة', 'The year 2018 was defined by a severe humanitarian crisis and significant economic and political events. The Saudi-led coalition deposited **$2 billion** into the Central Bank of Yemen (CBY) in March, which temporarily stabilized the Yemeni Rial and curbed hyperinflation. However, the conflict escalated dramatically with the start of the **Battle of Hodeidah** in June, threatening the country''s main port and humanitarian lifeline. The year concluded with the **Stockholm Agreement** in December, which established a ceasefire in Hodeidah and provided a fragile political breakthrough. The overall economic situation remained dire, with a small positive GDP growth of **0.8%** following years of contraction, and inflation remaining high at **33.65%**.', 'The year 2018 was defined by a severe humanitarian crisis and significant economic and political events. The Saudi-led coalition deposited **$2 billion** into the Central Bank of Yemen (CBY) in March, which temporarily stabilized the Yemeni Rial and curbed hyperinflation. However, the conflict escalated dramatically with the start of the **Battle of Hodeidah** in June, threatening the country''s main port and humanitarian lifeline. The year concluded with the **Stockholm Agreement** in December, which established a ceasefire in Hodeidah and provided a fragile political breakthrough. The overall economic situation remained dire, with a small positive GDP growth of **0.8%** following years of contraction, and inflation remaining high at **33.65%**.', '2018-12-31', 'economic', 'high', 'World Bank, Exchange-Rates.org, Statista, UN OCHA FTS, IPC, UNHCR, Saudi Ministry of Finance, Al Jazeera, ACAPS', 'year-2018,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Saudi $2B deposit in CBY (March 2018)', 'Saudi $2B deposit in CBY (March 2018)', 'Saudi $2B deposit in CBY (March 2018) led to Temporary stabilization of the Yemeni Rial. YER) and curb on hyperinflation (quantified impact: YER/USD rate stabilized around 250 after deposit', 'Saudi $2B deposit in CBY (March 2018) led to Temporary stabilization of the Yemeni Rial. YER) and curb on hyperinflation (quantified impact: YER/USD rate stabilized around 250 after deposit', '2018-06-30', 'political', 'medium', 'World Bank, Exchange-Rates.org, Statista, UN OCHA FTS, IPC, UNHCR, Saudi Ministry of Finance, Al Jazeera, ACAPS', 'year-2018,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Battle of Hodeidah (June 2018)', 'Battle of Hodeidah (June 2018)', 'Battle of Hodeidah (June 2018) led to Increased humanitarian crisis and threat to food imports. quantified impact: 15.9M severely food insecure', 'Battle of Hodeidah (June 2018) led to Increased humanitarian crisis and threat to food imports. quantified impact: 15.9M severely food insecure', '2018-06-30', 'political', 'medium', 'World Bank, Exchange-Rates.org, Statista, UN OCHA FTS, IPC, UNHCR, Saudi Ministry of Finance, Al Jazeera, ACAPS', 'year-2018,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict and economic collapse', 'Conflict and economic collapse', 'Conflict and economic collapse led to 33.65% annual inflation rate. quantified impact: 33.65% annual inflation', 'Conflict and economic collapse led to 33.65% annual inflation rate. quantified impact: 33.65% annual inflation', '2018-06-30', 'political', 'medium', 'World Bank, Exchange-Rates.org, Statista, UN OCHA FTS, IPC, UNHCR, Saudi Ministry of Finance, Al Jazeera, ACAPS', 'year-2018,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2020 - Year in Review', 'اقتصاد اليمن 2020 - مراجعة السنة', 'The year 2020 was marked by a severe economic contraction, with preliminary estimates suggesting an 8.5% shrinkage in GDP, primarily driven by the compounding effects of the ongoing conflict, economic fragmentation, and the global COVID-19 pandemic. The conflict continued with a major Houthi offensive on Marib, while the economic divide deepened with a significant divergence between the nominal official exchange rate of 250 YER/USD and the parallel market rate, which averaged around 772 YER/USD in Aden. The humanitarian crisis intensified, with 16.2 million people facing food insecurity and the total stock of internally displaced persons (IDPs) reaching 4 million since 2015, all while the $3.38 billion humanitarian appeal was only 58.9% funded. Fiscal policy remained constrained, with the Internationally Recognized Government relying on money printing to cover expenditures due to underperforming public revenue and slow oil production recovery.', 'The year 2020 was marked by a severe economic contraction, with preliminary estimates suggesting an 8.5% shrinkage in GDP, primarily driven by the compounding effects of the ongoing conflict, economic fragmentation, and the global COVID-19 pandemic. The conflict continued with a major Houthi offensive on Marib, while the economic divide deepened with a significant divergence between the nominal official exchange rate of 250 YER/USD and the parallel market rate, which averaged around 772 YER/USD in Aden. The humanitarian crisis intensified, with 16.2 million people facing food insecurity and the total stock of internally displaced persons (IDPs) reaching 4 million since 2015, all while the $3.38 billion humanitarian appeal was only 58.9% funded. Fiscal policy remained constrained, with the Internationally Recognized Government relying on money printing to cover expenditures due to underperforming public revenue and slow oil production recovery.', '2020-12-31', 'economic', 'high', 'World Bank, IMF, Statista, ReliefWeb, UN OCHA, IOM, Human Rights Watch, PMC, EU Factsheet', 'year-2020,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('COVID-19 pandemic', 'COVID-19 pandemic', 'COVID-19 pandemic led to Non-oil economic activity slowdown. World Bank', 'COVID-19 pandemic led to Non-oil economic activity slowdown. World Bank', '2020-06-30', 'political', 'medium', 'World Bank, IMF, Statista, ReliefWeb, UN OCHA, IOM, Human Rights Watch, PMC, EU Factsheet', 'year-2020,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict/Dual Taxation/COVID-19', 'Conflict/Dual Taxation/COVID-19', 'Conflict/Dual Taxation/COVID-19 led to GDP shrinkage of -8.5%. World Bank', 'Conflict/Dual Taxation/COVID-19 led to GDP shrinkage of -8.5%. World Bank', '2020-06-30', 'political', 'medium', 'World Bank, IMF, Statista, ReliefWeb, UN OCHA, IOM, Human Rights Watch, PMC, EU Factsheet', 'year-2020,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict/Economic Fragmentation', 'Conflict/Economic Fragmentation', 'Conflict/Economic Fragmentation led to Currency depreciation. World Bank', 'Conflict/Economic Fragmentation led to Currency depreciation. World Bank', '2020-06-30', 'political', 'medium', 'World Bank, IMF, Statista, ReliefWeb, UN OCHA, IOM, Human Rights Watch, PMC, EU Factsheet', 'year-2020,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Conflict/Economic Fragmentation/COVID-19', 'Conflict/Economic Fragmentation/COVID-19', 'Conflict/Economic Fragmentation/COVID-19 led to 16.2M food insecure. PMC', 'Conflict/Economic Fragmentation/COVID-19 led to 16.2M food insecure. PMC', '2020-06-30', 'political', 'medium', 'World Bank, IMF, Statista, ReliefWeb, UN OCHA, IOM, Human Rights Watch, PMC, EU Factsheet', 'year-2020,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2021 - Year in Review', 'اقتصاد اليمن 2021 - مراجعة السنة', 'The year 2021 was marked by a severe economic and humanitarian crisis, driven by the Houthi offensive on the strategic, oil-rich Marib governorate and a crippling fuel crisis. Macroeconomic fragmentation intensified, leading to the Yemeni Rial''s collapse in the IRG-controlled south, with the parallel market rate exceeding 1,700 YER/USD by December, fueling an estimated 45% inflation rate. The humanitarian situation remained the world''s worst, with 20.7 million people in need of aid and the IDP population reaching 4.3 million, while the UN''s $3.85 billion response plan remained significantly underfunded.', 'The year 2021 was marked by a severe economic and humanitarian crisis, driven by the Houthi offensive on the strategic, oil-rich Marib governorate and a crippling fuel crisis. Macroeconomic fragmentation intensified, leading to the Yemeni Rial''s collapse in the IRG-controlled south, with the parallel market rate exceeding 1,700 YER/USD by December, fueling an estimated 45% inflation rate. The humanitarian situation remained the world''s worst, with 20.7 million people in need of aid and the IDP population reaching 4.3 million, while the UN''s $3.85 billion response plan remained significantly underfunded.', '2021-12-31', 'economic', 'high', 'IMF DataMapper, FEWS NET, World Bank, UN OCHA, UNHCR, UN OCHA FTS, Sana''a Center, ACAPS', 'year-2021,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi offensive on Marib (Feb 2021)', 'Houthi offensive on Marib (Feb 2021)', 'Houthi offensive on Marib (Feb 2021) led to Displacement of thousands and threat to 25% of Yemen''s GDP (oil/gas revenue) [11] [12]. ', 'Houthi offensive on Marib (Feb 2021) led to Displacement of thousands and threat to 25% of Yemen''s GDP (oil/gas revenue) [11] [12]. ', '2021-06-30', 'political', 'medium', 'IMF DataMapper, FEWS NET, World Bank, UN OCHA, UNHCR, UN OCHA FTS, Sana''a Center, ACAPS', 'year-2021,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('IRG Central Bank policies / fragmentation', 'IRG Central Bank policies / fragmentation', 'IRG Central Bank policies / fragmentation led to YER depreciation in Aden → Parallel market exchange rate exceeding 1,700 YER/USD [2] [13]. ', 'IRG Central Bank policies / fragmentation led to YER depreciation in Aden → Parallel market exchange rate exceeding 1,700 YER/USD [2] [13]. ', '2021-06-30', 'political', 'medium', 'IMF DataMapper, FEWS NET, World Bank, UN OCHA, UNHCR, UN OCHA FTS, Sana''a Center, ACAPS', 'year-2021,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Currency depreciation and fuel crisis', 'Currency depreciation and fuel crisis', 'Currency depreciation and fuel crisis led to Annual inflation accelerating to 45% (World Bank estimate) [3]. ', 'Currency depreciation and fuel crisis led to Annual inflation accelerating to 45% (World Bank estimate) [3]. ', '2021-06-30', 'political', 'medium', 'IMF DataMapper, FEWS NET, World Bank, UN OCHA, UNHCR, UN OCHA FTS, Sana''a Center, ACAPS', 'year-2021,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Fuel crisis/blockade', 'Fuel crisis/blockade', 'Fuel crisis/blockade led to Increased cost of Minimum/Survivable Food Basket (52% in South, 19% in North) [3]. ', 'Fuel crisis/blockade led to Increased cost of Minimum/Survivable Food Basket (52% in South, 19% in North) [3]. ', '2021-06-30', 'political', 'medium', 'IMF DataMapper, FEWS NET, World Bank, UN OCHA, UNHCR, UN OCHA FTS, Sana''a Center, ACAPS', 'year-2021,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2022 - Year in Review', 'اقتصاد اليمن 2022 - مراجعة السنة', 'The year 2022 was defined by a significant political and security shift, beginning with the formation of the Presidential Leadership Council (PLC) in April, which consolidated the internationally recognized government''s leadership. Concurrently, a UN-brokered truce, also starting in April, led to a substantial de-escalation of conflict, contributing to a modest 1.5% GDP growth. However, this positive economic momentum was severely undermined in the latter half of the year when Houthi attacks on oil ports halted oil exports, crippling the PLC''s primary source of revenue. The humanitarian crisis remained dire, with over 19 million people requiring food assistance, while the dual central bank system continued to drive extreme fragmentation in the currency market.', 'The year 2022 was defined by a significant political and security shift, beginning with the formation of the Presidential Leadership Council (PLC) in April, which consolidated the internationally recognized government''s leadership. Concurrently, a UN-brokered truce, also starting in April, led to a substantial de-escalation of conflict, contributing to a modest 1.5% GDP growth. However, this positive economic momentum was severely undermined in the latter half of the year when Houthi attacks on oil ports halted oil exports, crippling the PLC''s primary source of revenue. The humanitarian crisis remained dire, with over 19 million people requiring food assistance, while the dual central bank system continued to drive extreme fragmentation in the currency market.', '2022-12-31', 'economic', 'high', 'World Bank, IMF, UN OCHA, FEWS, ACAPS, Wikipedia', 'year-2022,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('UN-brokered Truce (April 2022)', 'UN-brokered Truce (April 2022)', 'UN-brokered Truce (April 2022) led to Modest GDP Growth. 1.5%', 'UN-brokered Truce (April 2022) led to Modest GDP Growth. 1.5%', '2022-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, FEWS, ACAPS, Wikipedia', 'year-2022,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi Attacks on Oil Ports (Late 2022)', 'Houthi Attacks on Oil Ports (Late 2022)', 'Houthi Attacks on Oil Ports (Late 2022) led to Halt of Oil Exports. IRG revenue loss, $7.5B estimate', 'Houthi Attacks on Oil Ports (Late 2022) led to Halt of Oil Exports. IRG revenue loss, $7.5B estimate', '2022-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, FEWS, ACAPS, Wikipedia', 'year-2022,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Fiscal Fragmentation (Dual Central Banks)', 'Fiscal Fragmentation (Dual Central Banks)', 'Fiscal Fragmentation (Dual Central Banks) led to Widely Divergent Exchange Rates. Sana''a vs. Aden, 560 vs. 1200 YER/USD', 'Fiscal Fragmentation (Dual Central Banks) led to Widely Divergent Exchange Rates. Sana''a vs. Aden, 560 vs. 1200 YER/USD', '2022-06-30', 'political', 'medium', 'World Bank, IMF, UN OCHA, FEWS, ACAPS, Wikipedia', 'year-2022,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2023 - Year in Review', 'اقتصاد اليمن 2023 - مراجعة السنة', 'The year 2023 was defined by a fragile de-escalation driven by Saudi-Houthi talks, yet the economic and humanitarian crises deepened due to severe fiscal fragmentation. The Houthi-imposed blockade on oil exports caused a significant decline in the Internationally Recognized Government''s (IRG) revenues, exacerbating the banking crisis and leading to a stark divergence in inflation and exchange rates between IRG and Houthi-controlled areas. Real GDP contracted by an estimated 2.0%, while 21.6 million people remained in need of humanitarian assistance, underscoring the severe impact of the protracted conflict and economic warfare on the civilian population.', 'The year 2023 was defined by a fragile de-escalation driven by Saudi-Houthi talks, yet the economic and humanitarian crises deepened due to severe fiscal fragmentation. The Houthi-imposed blockade on oil exports caused a significant decline in the Internationally Recognized Government''s (IRG) revenues, exacerbating the banking crisis and leading to a stark divergence in inflation and exchange rates between IRG and Houthi-controlled areas. Real GDP contracted by an estimated 2.0%, while 21.6 million people remained in need of humanitarian assistance, underscoring the severe impact of the protracted conflict and economic warfare on the civilian population.', '2023-12-31', 'economic', 'high', 'IMF DataMapper, World Bank, UN OCHA, IOM, Sana''a Center for Strategic Studies, Crisis Group, Statista, Central Bank of Yemen (CBY)', 'year-2023,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi-imposed blockade on oil exports', 'Houthi-imposed blockade on oil exports', 'Houthi-imposed blockade on oil exports led to IRG fiscal revenue decline by over 30%. World Bank 2023', 'Houthi-imposed blockade on oil exports led to IRG fiscal revenue decline by over 30%. World Bank 2023', '2023-06-30', 'political', 'medium', 'IMF DataMapper, World Bank, UN OCHA, IOM, Sana''a Center for Strategic Studies, Crisis Group, Statista, Central Bank of Yemen (CBY)', 'year-2023,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Saudi-Houthi talks and UN mediation efforts', 'Saudi-Houthi talks and UN mediation efforts', 'Saudi-Houthi talks and UN mediation efforts led to Sustained, though fragile, de-escalation. Crisis Group 2023', 'Saudi-Houthi talks and UN mediation efforts led to Sustained, though fragile, de-escalation. Crisis Group 2023', '2023-06-30', 'political', 'medium', 'IMF DataMapper, World Bank, UN OCHA, IOM, Sana''a Center for Strategic Studies, Crisis Group, Statista, Central Bank of Yemen (CBY)', 'year-2023,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Currency depreciation in IRG-controlled areas', 'Currency depreciation in IRG-controlled areas', 'Currency depreciation in IRG-controlled areas led to Elevated inflation at 7.0% in Aden. World Bank 2023', 'Currency depreciation in IRG-controlled areas led to Elevated inflation at 7.0% in Aden. World Bank 2023', '2023-06-30', 'political', 'medium', 'IMF DataMapper, World Bank, UN OCHA, IOM, Sana''a Center for Strategic Studies, Crisis Group, Statista, Central Bank of Yemen (CBY)', 'year-2023,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Protracted conflict and economic fragmentation', 'Protracted conflict and economic fragmentation', 'Protracted conflict and economic fragmentation led to 21.6M people needing humanitarian assistance. OCHA 2023', 'Protracted conflict and economic fragmentation led to 21.6M people needing humanitarian assistance. OCHA 2023', '2023-06-30', 'political', 'medium', 'IMF DataMapper, World Bank, UN OCHA, IOM, Sana''a Center for Strategic Studies, Crisis Group, Statista, Central Bank of Yemen (CBY)', 'year-2023,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2024 - Year in Review', 'اقتصاد اليمن 2024 - مراجعة السنة', 'The year 2024 was defined by the significant escalation of the **Red Sea crisis**, where the Houthi movement''s attacks on international shipping lanes led to retaliatory military strikes by a US-led coalition, effectively freezing the fragile peace process. Economically, the country continued to suffer from a fragmented fiscal system and a sustained blockade on oil exports, resulting in a projected **GDP contraction of 1.0%** and an estimated **inflation rate of 27%**. The humanitarian crisis remained catastrophic, with **18.2 million people** requiring assistance and the Humanitarian Response Plan facing a massive **$2.7 billion funding gap**, further exacerbating acute food insecurity for over 17 million people.', 'The year 2024 was defined by the significant escalation of the **Red Sea crisis**, where the Houthi movement''s attacks on international shipping lanes led to retaliatory military strikes by a US-led coalition, effectively freezing the fragile peace process. Economically, the country continued to suffer from a fragmented fiscal system and a sustained blockade on oil exports, resulting in a projected **GDP contraction of 1.0%** and an estimated **inflation rate of 27%**. The humanitarian crisis remained catastrophic, with **18.2 million people** requiring assistance and the Humanitarian Response Plan facing a massive **$2.7 billion funding gap**, further exacerbating acute food insecurity for over 17 million people.', '2024-12-31', 'economic', 'high', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,annual-review');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi Red Sea attacks (starting late 2023)', 'Houthi Red Sea attacks (starting late 2023)', 'Houthi Red Sea attacks (starting late 2023) led to Disruption of global shipping and trade routes (quantified impact: Suez Canal traffic down 50% in early 2024) [3] [4]. ', 'Houthi Red Sea attacks (starting late 2023) led to Disruption of global shipping and trade routes (quantified impact: Suez Canal traffic down 50% in early 2024) [3] [4]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi Red Sea attacks', 'Houthi Red Sea attacks', 'Houthi Red Sea attacks led to US/UK military strikes on Houthi targets in Yemen (Operation Prosperity Guardian) [1]. ', 'Houthi Red Sea attacks led to US/UK military strikes on Houthi targets in Yemen (Operation Prosperity Guardian) [1]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi Red Sea attacks & US/UK strikes', 'Houthi Red Sea attacks & US/UK strikes', 'Houthi Red Sea attacks & US/UK strikes led to Freezing of Omani-facilitated peace talks between Houthis and Saudi Arabia [1] [7]. ', 'Houthi Red Sea attacks & US/UK strikes led to Freezing of Omani-facilitated peace talks between Houthis and Saudi Arabia [1] [7]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Houthi Red Sea attacks & oil export blockade', 'Houthi Red Sea attacks & oil export blockade', 'Houthi Red Sea attacks & oil export blockade led to Projected GDP contraction of 1.0% in 2024 (World Bank) [2]. ', 'Houthi Red Sea attacks & oil export blockade led to Projected GDP contraction of 1.0% in 2024 (World Bank) [2]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Oil export blockade & fiscal fragmentation', 'Oil export blockade & fiscal fragmentation', 'Oil export blockade & fiscal fragmentation led to Continued pressure on the Yemeni Rial and high inflation (estimated 27% in 2024) [2] [6]. ', 'Oil export blockade & fiscal fragmentation led to Continued pressure on the Yemeni Rial and high inflation (estimated 27% in 2024) [2] [6]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Severe funding cuts for humanitarian aid', 'Severe funding cuts for humanitarian aid', 'Severe funding cuts for humanitarian aid led to Deepening acute food insecurity in Government-controlled areas (quantified impact: 17.6M people facing acute food insecurity) [5]. ', 'Severe funding cuts for humanitarian aid led to Deepening acute food insecurity in Government-controlled areas (quantified impact: 17.6M people facing acute food insecurity) [5]. ', '2024-06-30', 'political', 'medium', 'World Bank, UN OCHA, IMF, Central Bank of Yemen (CBY), CSIS, Atlas Institute, Security Council Report, Human Rights Watch', 'year-2024,causation');

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, impactLevel, sources, tags)
VALUES ('Yemen Economy 2025 - Year in Review', 'اقتصاد اليمن 2025 - مراجعة السنة', 'Yemen''s economy remained under severe strain in 2025, marked by a projected real GDP contraction of 0.5% and inflation that surged above 35% by mid-year due to the rial''s 30% weakening. The political landscape remained stalled, with the peace process failing to advance and the continued impact of Houthi attacks on oil facilities halting exports. The humanitarian crisis deepened, with 19.5 million people in need and the YHNRP 2025 only 24% funded by November, forcing the IRG to adopt FX stabilization measures in August to ease currency pressures.', 'Yemen''s economy remained under severe strain in 2025, marked by a projected real GDP contraction of 0.5% and inflation that surged above 35% by mid-year due to the rial''s 30% weakening. The political landscape remained stalled, with the peace process failing to advance and the continued impact of Houthi attacks on oil facilities halting exports. The humanitarian crisis deepened, with 19.5 million people in need and the YHNRP 2025 only 24% funded by November, forcing the IRG to adopt FX stabilization measures in August to ease currency pressures.', '2025-12-31', 'economic', 'high', 'IMF, World Bank, UN OCHA, IOM DTM, IPC, Central Bank of Yemen (CBY), Trading Economics, Statista, Joint Data Center (JDC)', 'year-2025,annual-review');

