-- Comprehensive Research Events Insertions
-- Total events: 46

INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2010', 'أحداث رئيسية 2010', 'Yemen in 2010 was marked by economic fragility, with 7.7% GDP growth but high inflation (9.8%) and widespread poverty (46.6% at $2/day). The economy was heavily dependent on rapidly dwindling oil revenues, which caused a record fiscal deficit (10% of GDP in 2009) and a widening current account deficit. Political instability, including a fragile Houthi ceasefire and rising southern separatism, severely complicated necessary economic reform efforts.', 'ملخص: Yemen in 2010 was marked by economic fragility, with 7.7% GDP growth but high inflation (9.8%) and widespread poverty (46.6% at $2/day). The economy was heavily dependent on rapidly dwindling oil reve', '2010-01-01', 'economic', 'high', '["World Bank, IMF, Bertelsmann Transformation Index (BTI)"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2011', 'أحداث رئيسية 2011', 'The 2011 revolution in Yemen, driven by protests against President Ali Abdullah Saleh, caused a severe economic shock. Real GDP contracted by 12.0%, inflation surged to 19.5%, and oil production was disrupted. The political crisis culminated in the signing of the GCC Initiative in November, but the resulting political instability led to a major humanitarian crisis with over 416,000 internally displaced persons.', 'ملخص: The 2011 revolution in Yemen, driven by protests against President Ali Abdullah Saleh, caused a severe economic shock. Real GDP contracted by 12.0%, inflation surged to 19.5%, and oil production was d', '2011-01-01', 'economic', 'high', '["Atlantic Council, UN OCHA, Macrotrends, IndexMundi"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2012', 'أحداث رئيسية 2012', 'Yemen''s 2012 transition, marked by Hadi''s presidency, saw a modest economic rebound (2.4% GDP growth) from the 2011 crisis, driven by improved security and donor support. However, the country faced severe macroeconomic instability, evidenced by a high fiscal deficit (9.4% of GDP) and persistent humanitarian crisis, with an estimated 10 million people food insecure and unemployment soaring to 29.2%. International donors pledged nearly $8 billion to support the Transitional Program for Stabilizati', 'ملخص: Yemen''''s 2012 transition, marked by Hadi''''s presidency, saw a modest economic rebound (2.4% GDP growth) from the 2011 crisis, driven by improved security and donor support. However, the country faced ', '2012-01-01', 'economic', 'high', '["World Bank, International Monetary Fund (IMF), United Nations Development Programme (UNDP), Gulf Cooperation Council (GCC)"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2013', 'أحداث رئيسية 2013', 'Yemen in 2013 was characterized by a fragile political transition, marked by the start of the National Dialogue Conference (NDC), alongside significant economic challenges. Key economic indicators showed a rebound in Real GDP (6.0%) and hydrocarbon GDP (26.2%) following the 2011 crisis, but inflation remained high at 12.0%, and the total unemployment rate was estimated at 13.67%. The economy was heavily reliant on external donor support, notably the $8 billion pledged by the Friends of Yemen gro', 'ملخص: Yemen in 2013 was characterized by a fragile political transition, marked by the start of the National Dialogue Conference (NDC), alongside significant economic challenges. Key economic indicators sho', '2013-01-01', 'economic', 'high', '["IMF, World Bank, ILO, Atlantic Council"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2014', 'أحداث رئيسية 2014', 'The 2014 crisis was immediately triggered by the government''s IMF-advised fuel subsidy removal in July, aimed at addressing a severe fiscal deficit. The Houthi movement exploited this economic shock, leading to mass protests and the military takeover of Sana''a on September 21, 2014. This event, built on pre-existing vulnerabilities like a 49% poverty rate, initiated the major escalation of the civil war and led to a sharp economic decline.', 'ملخص: The 2014 crisis was immediately triggered by the government''''s IMF-advised fuel subsidy removal in July, aimed at addressing a severe fiscal deficit. The Houthi movement exploited this economic shock,', '2014-01-01', 'economic', 'high', '["International Monetary Fund, World Bank, UN OCHA"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2015', 'أحداث رئيسية 2015', 'The 2015 war, initiated by Operation Decisive Storm, caused an immediate and severe economic collapse, with real GDP contracting by nearly 28%. Despite the conflict, the Central Bank of Yemen (CBY) in Sana''a maintained a critical, neutral function throughout 2015, paying public salaries and stabilizing the currency at 215 YER/US$1, which temporarily mitigated a worse humanitarian crisis. The economic war was characterized by a coalition blockade and the CBY''s struggle to manage foreign reserves,', 'ملخص: The 2015 war, initiated by Operation Decisive Storm, caused an immediate and severe economic collapse, with real GDP contracting by nearly 28%. Despite the conflict, the Central Bank of Yemen (CBY) in', '2015-01-01', 'economic', 'high', '["Sana''a Center for Strategic Studies, World Bank, International Monetary Fund, UN OCHA"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2016', 'أحداث رئيسية 2016', 'The 2016 CBY split was a political decision to weaponize the economy, leading to hyperinflation (254.9%), a 26% exchange rate divergence, and the collapse of public salary payments. This financial shock drove the poverty rate to an estimated 70.9% and rapidly accelerated the pre-existing humanitarian catastrophe.', 'ملخص: The 2016 CBY split was a political decision to weaponize the economy, leading to hyperinflation (254.9%), a 26% exchange rate divergence, and the collapse of public salary payments. This financial sho', '2016-01-01', 'economic', 'high', '["World Bank, IMF, UN OCHA, Sana''a Center"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2017', 'أحداث رئيسية 2017', 'The year 2017 was marked by a devastating cholera outbreak (450,000 suspected cases by Aug) and a deepening economic crisis. The 2016 Central Bank split led to a dual banking system, exacerbating economic fragmentation and contributing to a sharp rise in inflation (24.7% annual). The conflict caused an estimated 37.5% cumulative GDP contraction since 2015, severely undermining public services and household income. Humanitarian aid, led by UN agencies, was critical but underfunded.', 'ملخص: The year 2017 was marked by a devastating cholera outbreak (450,000 suspected cases by Aug) and a deepening economic crisis. The 2016 Central Bank split led to a dual banking system, exacerbating econ', '2017-01-01', 'economic', 'high', '["World Bank, UN OCHA, WHO, Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2018', 'أحداث رئيسية 2018', 'The 2018 crisis was driven by the CBY split, leading to expansive monetary policy and a fiscal deficit. This caused the Yemeni Rial to collapse, reaching 800 YR/USD in October, and fueled inflation estimated at over 40%. The economic collapse severely exacerbated the humanitarian catastrophe, with 22.2 million people in need of aid, despite a $2 billion deposit from KSA to stabilize the currency.', 'ملخص: The 2018 crisis was driven by the CBY split, leading to expansive monetary policy and a fiscal deficit. This caused the Yemeni Rial to collapse, reaching 800 YR/USD in October, and fueled inflation es', '2018-01-01', 'economic', 'high', '["World Bank, UN OCHA, Sana''a Center for Strategic Studies, Norwegian Refugee Council"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2019', 'أحداث رئيسية 2019', 'The year 2019 was defined by the **Riyadh Agreement** between the Hadi government and the STC, and the **Houthi currency ban** in Sana''a. The political agreement temporarily stabilized the rial, while the currency ban created a **dual exchange rate crisis** and a payment crisis in the North. The humanitarian situation remained the world''s worst, with 24.1 million people needing aid and 10 million facing severe food insecurity.', 'ملخص: The year 2019 was defined by the **Riyadh Agreement** between the Hadi government and the STC, and the **Houthi currency ban** in Sana''''a. The political agreement temporarily stabilized the rial, whil', '2019-01-01', 'economic', 'high', '["World Bank, UN OCHA, Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2020', 'أحداث رئيسية 2020', 'Yemen''s economy contracted by 8.5% in 2020, driven by the COVID-19-induced decline in remittances and trade, and compounded by conflict-related fiscal fragmentation. Aid obstruction led to significant donor funding cuts, worsening the already severe humanitarian crisis and pushing inflation to 35.0%.', 'ملخص: Yemen''''s economy contracted by 8.5% in 2020, driven by the COVID-19-induced decline in remittances and trade, and compounded by conflict-related fiscal fragmentation. Aid obstruction led to significan', '2020-01-01', 'economic', 'high', '["World Bank, Human Rights Watch, UN OCHA, IFPRI"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2021', 'أحداث رئيسية 2021', 'Yemen''s economic and humanitarian crisis deepened in 2021, driven by the fragmentation of the Central Bank of Yemen and the resulting currency war, which saw the riyal depreciate to historic lows and inflation soar (e.g., food basket cost up 52% in the South). The severe fuel crisis, marked by a 72% decline in Hodeidah fuel imports, compounded the crisis, leaving 20.7 million people in need of humanitarian assistance. Key policy responses included a US$660 million IMF SDR allocation and the CBY-', 'ملخص: Yemen''''s economic and humanitarian crisis deepened in 2021, driven by the fragmentation of the Central Bank of Yemen and the resulting currency war, which saw the riyal depreciate to historic lows and', '2021-01-01', 'economic', 'high', '["World Bank, UN OCHA, Central Bank of Yemen, IMF"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2022', 'أحداث رئيسية 2022', 'The 2022 UN truce provided a significant economic breathing space, mainly through a massive increase in fuel imports via Hodeidah port, which lowered distribution costs in Houthi-controlled areas. The truce also saw the stabilization of the Yemeni rial in IRG areas, supported by a $2 billion pledge from Saudi Arabia and the UAE. The truce''s expiration led to renewed economic warfare, notably Houthi attacks on oil exports.', 'ملخص: The 2022 UN truce provided a significant economic breathing space, mainly through a massive increase in fuel imports via Hodeidah port, which lowered distribution costs in Houthi-controlled areas. The', '2022-01-01', 'economic', 'high', '["World Bank, Sana''a Center for Strategic Studies, ACAPS, UN OCHA"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2023', 'أحداث رئيسية 2023', 'Yemen''s economy contracted by 2.0% in 2023, primarily due to the Houthi-imposed oil export blockade which caused a sharp decline in IRG fiscal revenues and widened the current account deficit to 19.3% of GDP. The subsequent Houthi attacks in the Red Sea starting in late 2023 further strained the import-dependent economy through increased shipping costs, exacerbating the existing monetary fragmentation and exchange rate pressure in IRG-controlled areas.', 'ملخص: Yemen''''s economy contracted by 2.0% in 2023, primarily due to the Houthi-imposed oil export blockade which caused a sharp decline in IRG fiscal revenues and widened the current account deficit to 19.3', '2023-01-01', 'economic', 'high', '["World Bank, International Monetary Fund (IMF), Council on Foreign Relations (CFR)"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2024', 'أحداث رئيسية 2024', 'Yemen''s economy in 2024 was defined by severe fragmentation and external shocks. Real GDP was projected to contract by 1.0%, driven by the Houthi blockade on IRG oil exports, which caused a 42% fiscal revenue drop. The split Central Bank exacerbated the exchange rate crisis, with the rial depreciating to 1,917 YER/USD in Aden by August. Houthi Red Sea attacks increased import costs, while 18.2 million people required humanitarian aid amidst threats of major donor cuts.', 'ملخص: Yemen''''s economy in 2024 was defined by severe fragmentation and external shocks. Real GDP was projected to contract by 1.0%, driven by the Houthi blockade on IRG oil exports, which caused a 42% fisca', '2024-01-01', 'economic', 'high', '["World Bank, IMF, UN OCHA, Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Major Events 2025', 'أحداث رئيسية 2025', 'Yemen''s 2025 outlook is bleak, marked by severe economic fragmentation and a deepening humanitarian crisis. GDP is projected to contract by 0.5% to 1.5%, driven by the oil export blockade and declining aid, which has left the UN''s $2.5B humanitarian plan only 19% funded. The currency crisis, with a YER/USD rate split between 534 and 1,676, highlights the institutional division and economic warfare between the conflicting parties.', 'ملخص: Yemen''''s 2025 outlook is bleak, marked by severe economic fragmentation and a deepening humanitarian crisis. GDP is projected to contract by 0.5% to 1.5%, driven by the oil export blockade and declini', '2025-01-01', 'economic', 'high', '["World Bank, IMF, UN OCHA, Sana''a Center for Strategic Studies, IRIS-France, Trading Economics"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('World Bank Yemen: All projects, funding, reports, Emergency Crisis Response Project, Financial Marke', 'World Bank Yemen: All projects, funding, reports, Emergency Crisis Response Project, Financial Marke', 'The World Bank''s ECRP has provided over $860 million in grants for crisis mitigation. Recent years show severe economic contraction (-1.5% GDP in 2025) and high inflation (35%+ in 2025) driven by conflict, fiscal fragmentation, and Red Sea tensions. New projects focus on digital financial infrastructure and education.', 'ملخص: The World Bank''''s ECRP has provided over $860 million in grants for crisis mitigation. Recent years show severe economic contraction (-1.5% GDP in 2025) and high inflation (35%+ in 2025) driven by con', '2020-01-01', 'international', 'high', '["World Bank, IMF, UNDP, UNICEF"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('IMF Yemen: Article IV consultations, programs, technical assistance, reports, economic assessments, ', 'IMF Yemen: Article IV consultations, programs, technical assistance, reports, economic assessments, ', 'The IMF''s engagement with Yemen was centered on the 2014 Article IV Consultation and a proposed Extended Credit Facility (ECF) to address a deteriorating macroeconomic situation, primarily caused by oil pipeline sabotage and political instability. The core policy focus was a substantial overhaul of energy subsidies to free up funds for social transfers and infrastructure. The IMF''s formal Article IV consultations resumed in 2025 after an 11-year hiatus, highlighting the severe disruption of the ', 'ملخص: The IMF''''s engagement with Yemen was centered on the 2014 Article IV Consultation and a proposed Extended Credit Facility (ECF) to address a deteriorating macroeconomic situation, primarily caused by ', '2020-01-01', 'international', 'high', '["International Monetary Fund, World Bank"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UN OCHA Yemen: Humanitarian Response Plans, funding appeals, crisis reports, coordination, needs ass', 'UN OCHA Yemen: Humanitarian Response Plans, funding appeals, crisis reports, coordination, needs ass', 'The Yemen crisis is characterized by a massive and sustained humanitarian need, with over 19 million people requiring assistance in 2025. The primary drivers are protracted conflict, severe economic collapse, and recurrent climate shocks. Despite billions in requirements, the annual response plans consistently face severe underfunding, highlighting a critical gap between humanitarian needs and available resources.', 'ملخص: The Yemen crisis is characterized by a massive and sustained humanitarian need, with over 19 million people requiring assistance in 2025. The primary drivers are protracted conflict, severe economic c', '2020-01-01', 'economic', 'high', '["UN OCHA, ReliefWeb, FAO, IOM, UNICEF, WHO"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('WFP Yemen: Food assistance programs, beneficiaries, funding, reports, food security assessments, ope', 'WFP Yemen: Food assistance programs, beneficiaries, funding, reports, food security assessments, ope', 'WFP Yemen''s 2024 operations were marked by a significant policy shift from General Food Assistance to Targeted Emergency Food Assistance, assisting 7.2 million people. The program faced major disruptions, including a pause in the Sana''a-based authorities (SBA) areas and operational challenges due to Red Sea attacks and severe climate-related floods. Funding shortfalls remain a critical constraint, forcing a more targeted approach.', 'ملخص: WFP Yemen''''s 2024 operations were marked by a significant policy shift from General Food Assistance to Targeted Emergency Food Assistance, assisting 7.2 million people. The program faced major disrupt', '2020-01-01', 'international', 'high', '["World Food Programme, ReliefWeb, World Bank, IPC"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UNHCR Yemen: Refugee and IDP data, protection, assistance programs, reports, displacement statistics', 'UNHCR Yemen: Refugee and IDP data, protection, assistance programs, reports, displacement statistics', 'The Yemen crisis is characterized by severe economic hardship and growing fragmentation, with real GDP projected to contract by 1.5% in 2025, driven by the oil export blockade and institutional division. UNHCR data shows nearly 4.8 million internally displaced persons (IDPs) and 21.6 million people in need of humanitarian aid, while funding for the UN response remains critically low at 19% of the required $2.5 billion. The economic decline is directly linked to conflict, leading to a 26% increas', 'ملخص: The Yemen crisis is characterized by severe economic hardship and growing fragmentation, with real GDP projected to contract by 1.5% in 2025, driven by the oil export blockade and institutional divisi', '2020-01-01', 'economic', 'high', '["UNHCR, World Bank, IOM, TFPM"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UNICEF Yemen: Child welfare, education, health, nutrition, WASH programs, reports, statistics', 'UNICEF Yemen: Child welfare, education, health, nutrition, WASH programs, reports, statistics', 'UNICEF''s response in Yemen is critical, with 9.8 million children in need of assistance due to conflict and economic collapse. Key programmatic results for the first half of 2024 include screening 1.7 million children for malnutrition and reaching 1.3 million people with mine risk education, highlighting the severe humanitarian and protection challenges. The high stunting rate (47%) and low birth registration (29%) underscore the long-term development crisis.', 'ملخص: UNICEF''''s response in Yemen is critical, with 9.8 million children in need of assistance due to conflict and economic collapse. Key programmatic results for the first half of 2024 include screening 1.', '2020-01-01', 'international', 'high', '["UNICEF, UNICEF Data"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('WHO Yemen: Health system, disease outbreaks, cholera, COVID-19, health facilities, reports', 'WHO Yemen: Health system, disease outbreaks, cholera, COVID-19, health facilities, reports', 'The Yemen health system is severely strained, with only 38% of facilities partially functioning as of late 2024. Major events include the 2016-2022 cholera outbreak, the COVID-19 pandemic, and recent floods. Key indicators show high rates of malnutrition and a massive cholera burden, with WHO and partners struggling due to chronic underfunding.', 'ملخص: The Yemen health system is severely strained, with only 38% of facilities partially functioning as of late 2024. Major events include the 2016-2022 cholera outbreak, the COVID-19 pandemic, and recent ', '2020-01-01', 'international', 'high', '["World Health Organization (WHO), ReliefWeb, The Lancet, World Bank"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('FAO Yemen: Food security, agriculture, livestock, fisheries, reports, assessments, projects', 'FAO Yemen: Food security, agriculture, livestock, fisheries, reports, assessments, projects', 'The food security situation in Yemen remains critical, with IPC Phase 5 (Catastrophe) projected for parts of the country in 2025, driven by the ongoing conflict, economic decline, and climate shocks. FAO''s strategy involves emergency aid, resilience-building projects, and continuous monitoring of agricultural livelihoods, supported by significant international funding.', 'ملخص: The food security situation in Yemen remains critical, with IPC Phase 5 (Catastrophe) projected for parts of the country in 2025, driven by the ongoing conflict, economic decline, and climate shocks. ', '2020-01-01', 'international', 'high', '["FAO, WFP, IPC, UN OCHA, World Bank"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UNDP Yemen: Development programs, governance, economic recovery, reports, projects', 'UNDP Yemen: Development programs, governance, economic recovery, reports, projects', 'The conflict in Yemen has resulted in a cumulative loss of $126 billion in potential GDP and 377,000 deaths by 2021, with 60% from indirect causes. UNDP''s research highlights that an integrated recovery strategy, focusing on women''s empowerment, agriculture, and private sector leverage, is essential to surpass the pre-war SDG trajectory by 2050. The ERRY Joint Programme (2016-2025) reached over 2.1 million Yemenis, strengthening livelihoods and local governance.', 'ملخص: The conflict in Yemen has resulted in a cumulative loss of $126 billion in potential GDP and 377,000 deaths by 2021, with 60% from indirect causes. UNDP''''s research highlights that an integrated recov', '2020-01-01', 'economic', 'high', '["United Nations Development Programme, Frederick S. Pardee Center, European Union, FAO, WFP, ILO"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('IOM Yemen: Migration, displacement, DTM reports, humanitarian assistance, protection', 'IOM Yemen: Migration, displacement, DTM reports, humanitarian assistance, protection', 'The protracted conflict and economic collapse in Yemen have created one of the world''s most severe humanitarian crises, with 19.5 million people in need of assistance in 2025. Key economic indicators show a projected GDP contraction of -1.5% and high inflation (20.4%) for 2025. IOM''s DTM tracks over 3 million IDPs, with economic hardship and declining international aid being major drivers of displacement. The response focuses on multisectoral aid, protection, and building resilience.', 'ملخص: The protracted conflict and economic collapse in Yemen have created one of the world''''s most severe humanitarian crises, with 19.5 million people in need of assistance in 2025. Key economic indicators', '2020-01-01', 'international', 'high', '["International Organization for Migration (IOM), World Bank, International Monetary Fund (IMF), UN OCHA, CALP Network"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Central Bank Yemen Aden: All circulars, decisions, monetary policy, exchange rate policy, reports, a', 'Central Bank Yemen Aden: All circulars, decisions, monetary policy, exchange rate policy, reports, a', 'The Central Bank of Yemen (Aden) operates under a challenging dual-economy context, focusing on price stability through monetary targeting. Key events include the issuance of directives to increase bank capital and the ongoing struggle to stabilize the exchange rate. Data quality is limited due to the conflict, relying heavily on CBY''s own reports and international projections.', 'ملخص: The Central Bank of Yemen (Aden) operates under a challenging dual-economy context, focusing on price stability through monetary targeting. Key events include the issuance of directives to increase ba', '2020-01-01', 'international', 'high', '["Central Bank of Yemen (Aden), World Bank, International Monetary Fund (IMF), Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Central Bank Yemen Sana''a: All circulars, decisions, monetary policy, currency policies, operations ', 'Central Bank Yemen Sana''a: All circulars, decisions, monetary policy, currency policies, operations ', 'The CBY-Sana''a, under Houthi control, has aggressively pursued monetary control since the 2016 split, notably by banning CBY-Aden''s new banknotes in 2019 and issuing its own new coins and notes in 2024-2025. These unilateral actions, often in response to external pressure like the US FTO designation, have deepened the currency war, leading to a dual monetary system and significant instability in the Yemeni rial''s value in government-held areas. The core mechanism is the assertion of financial so', 'ملخص: The CBY-Sana''''a, under Houthi control, has aggressively pursued monetary control since the 2016 split, notably by banning CBY-Aden''''s new banknotes in 2019 and issuing its own new coins and notes in 2', '2020-01-01', 'war', 'high', '["Sana''a Center for Strategic Studies, World Bank, ODI"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen commercial banks: CAC Bank, Yemen Kuwait Bank, Tadhamon, Yemen Commercial Bank, National Bank,', 'Yemen commercial banks: CAC Bank, Yemen Kuwait Bank, Tadhamon, Yemen Commercial Bank, National Bank,', 'The Yemeni banking sector is severely fragmented due to the dual Central Bank system and the Houthi-imposed anti-usury law (March 2023). This has led to a sharp decline in local currency deposits (from 15.1% of GDP in 2014 to 9.4% in 2023) and put major commercial banks like CAC Bank and National Bank of Yemen at risk of capital depletion. Key actors, including Yemen Kuwait Bank, have faced US sanctions (Jan 2025) for supporting the Houthis, further isolating the formal financial system.', 'ملخص: The Yemeni banking sector is severely fragmented due to the dual Central Bank system and the Houthi-imposed anti-usury law (March 2023). This has led to a sharp decline in local currency deposits (fro', '2020-01-01', 'economic', 'high', '["World Bank, ACAPS, Tadhamon Bank, US Department of the Treasury"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen Islamic banks: Shamil Bank, Saba Islamic Bank, Yemen Islamic Bank, operations, reports, status', 'Yemen Islamic banks: Shamil Bank, Saba Islamic Bank, Yemen Islamic Bank, operations, reports, status', 'The three Islamic banks operate in a severely fragmented and high-risk environment, dominated by the dual Central Bank system and the Houthi-enacted Anti-Usury Law of 2023. This law, which bans interest, threatens bank stability by forcing write-downs on government securities, a major source of revenue. The banks are also caught in the CBY-Aden''s 2024 order for Sana''a-based banks to relocate, deepening the sector''s political division. Financial data is scarce and dated, suggesting very limited t', 'ملخص: The three Islamic banks operate in a severely fragmented and high-risk environment, dominated by the dual Central Bank system and the Houthi-enacted Anti-Usury Law of 2023. This law, which bans intere', '2020-01-01', 'economic', 'high', '["World Bank, Central Bank of Yemen, ACAPS, Shamil Bank of Yemen and Bahrain"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen Microfinance Network: All member institutions, reports, statistics, borrowers, depositors, ope', 'Yemen Microfinance Network: All member institutions, reports, statistics, borrowers, depositors, ope', 'The Yemen Microfinance Network (YMN) and its members have faced severe operational challenges due to the war and COVID-19, with a significant drop in loan issuance in 2020. The Social Fund for Development (SFD) and YMN''s intervention helped restore 4,738 war-affected enterprises. Data on borrowers and savers is available, but detailed financial performance metrics like Portfolio at Risk are only available per MFI, not aggregated.', 'ملخص: The Yemen Microfinance Network (YMN) and its members have faced severe operational challenges due to the war and COVID-19, with a significant drop in loan issuance in 2020. The Social Fund for Develop', '2020-01-01', 'international', 'high', '["Yemen Microfinance Network (YMN), Social Fund for Development (SFD), World Bank, San''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Social Fund for Development Yemen: Projects, funding, microfinance programs, reports, impact', 'Social Fund for Development Yemen: Projects, funding, microfinance programs, reports, impact', 'The Social Fund for Development (SFD) Yemen has proven to be a highly resilient and effective national institution, managing over $1.75B in cumulative disbursements since 1997. Despite the 2015 conflict severely impacting its microfinance sector, SFD remains a critical partner for major donors like the World Bank, which approved a $207M grant in 2023 for social protection, underscoring SFD''s central role in Yemen''s humanitarian and development landscape.', 'ملخص: The Social Fund for Development (SFD) Yemen has proven to be a highly resilient and effective national institution, managing over $1.75B in cumulative disbursements since 1997. Despite the 2015 confli', '2020-01-01', 'international', 'high', '["World Bank, Social Fund for Development, Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen money exchangers: Informal financial sector, operations, exchange rates, regulations, status', 'Yemen money exchangers: Informal financial sector, operations, exchange rates, regulations, status', 'The conflict and the 2016 CBY split forced a reliance on the informal financial sector, where money exchangers became the primary channel for remittances and trade finance. Despite their critical role, they exhibit low profitability (avg. ROA -0.4%) and face limited regulatory oversight, posing significant financial integrity risks due to the dual-authority environment.', 'ملخص: The conflict and the 2016 CBY split forced a reliance on the informal financial sector, where money exchangers became the primary channel for remittances and trade finance. Despite their critical role', '2020-01-01', 'international', 'high', '["World Bank, ODI, Sana''a Center for Strategic Studies"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen Tax and Customs Authority: Policies, revenues, reforms, reports, both Aden and Sana''a authorit', 'Yemen Tax and Customs Authority: Policies, revenues, reforms, reports, both Aden and Sana''a authorit', 'The Yemen Tax and Customs Authority is fragmented, with the Houthi-controlled Sana''a authority collecting an estimated $789 million in customs revenue from Red Sea ports, which funds their military operations. This dual control and the IRG''s customs dollar rate increases have caused economic division, a shift in import activity away from Aden, and triggered US sanctions targeting Houthi financial networks.', 'ملخص: The Yemen Tax and Customs Authority is fragmented, with the Houthi-controlled Sana''''a authority collecting an estimated $789 million in customs revenue from Red Sea ports, which funds their military o', '2020-01-01', 'war', 'high', '["Sana''a Center For Strategic Studies, World Bank, IMF"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('US sanctions Yemen: OFAC designations, Houthi sanctions, financial restrictions, reports, impact', 'US sanctions Yemen: OFAC designations, Houthi sanctions, financial restrictions, reports, impact', 'US sanctions, including the FTO designation and targeted OFAC actions against 32 entities, have intensified financial pressure on the Houthis, targeting their illicit revenue from state capture, oil smuggling, and weapons procurement. However, the sanctions have also exacerbated Yemen''s economic fragmentation, contributing to a sharp YER depreciation in IRG areas (to 2,065 YER/USD in 2024) and high inflation (30.4%), while humanitarian aid has declined. The World Bank estimates a 1.5% GDP contra', 'ملخص: US sanctions, including the FTO designation and targeted OFAC actions against 32 entities, have intensified financial pressure on the Houthis, targeting their illicit revenue from state capture, oil s', '2020-01-01', 'policy', 'high', '["US Department of the Treasury, World Bank, Sana''a Center for Strategic Studies, The New Humanitarian"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('EU sanctions Yemen: Sanctions list, arms embargo, financial measures, reports', 'EU sanctions Yemen: Sanctions list, arms embargo, financial measures, reports', 'The EU''s restrictive measures against Yemen, established in 2014, are primarily a transposition of the UN Security Council''s sanctions, focusing on a targeted arms embargo, asset freezes, and travel bans. The sanctions list is small, containing only 10 individuals and 1 entity, reflecting a focus on key destabilizing actors rather than broad economic measures. The economic impact is largely indirect, exacerbated by the civil war and the recent Houthi attacks in the Red Sea, which have contribute', 'ملخص: The EU''''s restrictive measures against Yemen, established in 2014, are primarily a transposition of the UN Security Council''''s sanctions, focusing on a targeted arms embargo, asset freezes, and travel', '2020-01-01', 'policy', 'high', '["UN Security Council, World Bank, IMF, European Union"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UK sanctions Yemen: Designations, financial restrictions, reports, coordination with UN', 'UK sanctions Yemen: Designations, financial restrictions, reports, coordination with UN', 'UK sanctions target 11 Houthi leaders for actions like supporting Red Sea attacks and human rights abuses, with an asset freeze based on UN resolutions. The Houthi oil blockade and Red Sea attacks have exacerbated Yemen''s economic fragmentation, leading to a sharp decline in GDP per capita and a severe humanitarian crisis. UN reports highlight persistent arms embargo violations and the Houthis'' use of illegal revenue generation, limiting the effectiveness of financial sanctions.', 'ملخص: UK sanctions target 11 Houthi leaders for actions like supporting Red Sea attacks and human rights abuses, with an asset freeze based on UN resolutions. The Houthi oil blockade and Red Sea attacks hav', '2020-01-01', 'policy', 'high', '["HM Treasury, World Bank, UN Panel of Experts on Yemen"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UN Security Council Yemen: Resolutions, sanctions, arms embargo, Panel of Experts reports', 'UN Security Council Yemen: Resolutions, sanctions, arms embargo, Panel of Experts reports', 'The UN Security Council''s sanctions regime on Yemen, including the arms embargo and targeted financial measures, has been largely ineffective in curtailing the Houthi movement''s financial power. The Houthis, as the primary actor, have adapted by generating substantial revenue through illegal taxation, control of the telecommunications sector, and the seizure of commercial entities, with annual estimates from the telecom sector alone reaching approximately $92 million. This financial fragmentatio', 'ملخص: The UN Security Council''''s sanctions regime on Yemen, including the arms embargo and targeted financial measures, has been largely ineffective in curtailing the Houthi movement''''s financial power. The', '2020-01-01', 'policy', 'high', '["UN Panel of Experts on Yemen, World Bank, International Monetary Fund"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen territorial control map: Actor control by governorate, changes over time, military control', 'Yemen territorial control map: Actor control by governorate, changes over time, military control', 'Recent developments in December 2025 show a significant shift in the territorial control of southern Yemen, with the UAE-backed Southern Transitional Council (STC) seizing key areas in Hadramawt and Mahrah governorates, including vital oil infrastructure. This move further fragments the country and intensifies the economic war, which has already seen Yemen''s GDP contract by an accumulated 39% since 2014, according to the World Bank. The conflict remains centered on control over oil resources and', 'ملخص: Recent developments in December 2025 show a significant shift in the territorial control of southern Yemen, with the UAE-backed Southern Transitional Council (STC) seizing key areas in Hadramawt and M', '2020-01-01', 'war', 'high', '["ACLED, IMF, World Bank, Sana''a Center for Strategic Studies, The Soufan Center"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen actor funding sources: Houthis, IRG, STC, revenue sources, taxation, external support', 'Yemen actor funding sources: Houthis, IRG, STC, revenue sources, taxation, external support', 'The Houthis maintain a robust, multi-billion-dollar financial network through illicit oil trade, high port tariffs, and an estimated $180 million monthly from Red Sea shipping fees. This financial resilience, backed by Iran and Russia, has severely constrained the Internationally Recognized Government (IRG), whose primary oil revenue stream has collapsed to 2.5% of previous levels due to the Houthi blockade. Meanwhile, the UAE-backed Southern Transitional Council (STC) is consolidating control o', 'ملخص: The Houthis maintain a robust, multi-billion-dollar financial network through illicit oil trade, high port tariffs, and an estimated $180 million monthly from Red Sea shipping fees. This financial res', '2020-01-01', 'international', 'high', '["World Bank, IMF, GNET Research, UN"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Saudi Arabia Yemen support: Aid packages, deposits, projects, King Salman Center, military support', 'Saudi Arabia Yemen support: Aid packages, deposits, projects, King Salman Center, military support', 'Saudi Arabia has provided over $8 billion in financial aid and deposits to Yemen since 2012, with major CBY deposits totaling at least $4 billion aimed at currency stabilization. The Saudi-led military intervention, which began in March 2015, has been a major financial commitment. KSrelief has implemented 63 humanitarian projects worth over $345 million, providing a critical lifeline to the internationally recognized government.', 'ملخص: Saudi Arabia has provided over $8 billion in financial aid and deposits to Yemen since 2012, with major CBY deposits totaling at least $4 billion aimed at currency stabilization. The Saudi-led militar', '2020-01-01', 'international', 'high', '["Saudi Development and Reconstruction Program for Yemen, King Salman Humanitarian Aid and Relief Centre, International Monetary Fund, World Bank, Saudi Ministry of Finance"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('UAE Yemen involvement: Aid, STC support, port investments, economic projects, military role', 'UAE Yemen involvement: Aid, STC support, port investments, economic projects, military role', 'The UAE''s involvement in Yemen is characterized by a security-economic nexus, where military operations and support for the separatist Southern Transitional Council (STC) are intrinsically linked to securing strategic economic interests, particularly control over key maritime infrastructure and energy hubs in the south. Despite a 2019 military withdrawal, the UAE maintains significant influence through the STC and substantial financial aid, totaling over $6 billion between 2015 and 2020, and a r', 'ملخص: The UAE''''s involvement in Yemen is characterized by a security-economic nexus, where military operations and support for the separatist Southern Transitional Council (STC) are intrinsically linked to ', '2020-01-01', 'international', 'high', '["Carnegie Endowment for International Peace, ResearchGate, UAE Ministry of Foreign Affairs, New York Times"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('USA Yemen aid: USAID programs, humanitarian assistance, development projects, funding', 'USA Yemen aid: USAID programs, humanitarian assistance, development projects, funding', 'U.S. foreign assistance to Yemen is overwhelmingly humanitarian, with over $760 million obligated in the most recent reporting period, primarily channeled through the World Food Program and UN agencies. A critical policy event was the March 2020 partial suspension of USAID aid in northern Yemen due to Houthi interference, highlighting major actor-related challenges. Direct, comprehensive economic data for key indicators remains severely limited due to the ongoing conflict.', 'ملخص: U.S. foreign assistance to Yemen is overwhelmingly humanitarian, with over $760 million obligated in the most recent reporting period, primarily channeled through the World Food Program and UN agencie', '2020-01-01', 'international', 'high', '["USAID, U.S. Department of State, World Food Program, IMF, UN OCHA"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen transparency organizations: Yemen Data Project, ACAPS, Sana''a Center, DevChampions, reports', 'Yemen transparency organizations: Yemen Data Project, ACAPS, Sana''a Center, DevChampions, reports', 'Research confirms a severe and fragmented economic crisis in Yemen, driven by the Houthi oil export blockade and a sharp decline in international aid, leading to a projected -1.5% Real GDP contraction in 2025. Fiscal deterioration in IRG-controlled areas is marked by a 30% revenue decline and a doubling of the fiscal deficit, while monetary policy divergence continues to fuel high inflation and exchange rate volatility. Authoritative reports from the World Bank and Sana''a Center highlight the co', 'ملخص: Research confirms a severe and fragmented economic crisis in Yemen, driven by the Houthi oil export blockade and a sharp decline in international aid, leading to a projected -1.5% Real GDP contraction', '2020-01-01', 'policy', 'high', '["World Bank, IMF, Sana''a Center, ACAPS, Development Champions"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen donor coordination: UN coordination, donor conferences, funding pledges, disbursements', 'Yemen donor coordination: UN coordination, donor conferences, funding pledges, disbursements', 'The coordinated humanitarian response in Yemen is severely underfunded, with the 2025 plan only 24.2% funded, a situation exacerbated by a decade-long decline in donor commitments. This aid shortfall, combined with the oil export blockade and economic fragmentation, is projected to cause a 1.5% GDP decline and push over 60% of households into food insecurity.', 'ملخص: The coordinated humanitarian response in Yemen is severely underfunded, with the 2025 plan only 24.2% funded, a situation exacerbated by a decade-long decline in donor commitments. This aid shortfall,', '2020-01-01', 'economic', 'high', '["UN OCHA, World Bank, The Global Economy, European Commission, United Kingdom, Saudi Arabia, Germany, United States of America"]');
INSERT INTO events (titleEn, titleAr, descriptionEn, descriptionAr, date, category, severity, sources)
VALUES ('Yemen causation relationships: CBY split impact, war economic effects, sanctions impact, aid effecti', 'Yemen causation relationships: CBY split impact, war economic effects, sanctions impact, aid effecti', 'The CBY split in 2016 created two parallel economies, leading to severe currency divergence and economic fragmentation. The war caused a 54-58% decline in real GDP per capita since 2015. Sanctions, while targeted, have contributed to financial sector fragility. Aid effectiveness is hampered by the conflict, with cash assistance proving more efficient than food aid in some contexts. Data is highly fragmented and limited.', 'ملخص: The CBY split in 2016 created two parallel economies, leading to severe currency divergence and economic fragmentation. The war caused a 54-58% decline in real GDP per capita since 2015. Sanctions, wh', '2020-01-01', 'economic', 'high', '["World Bank, Sana''a Center for Strategic Studies, IMF, The New Humanitarian, UN Security Council"]');
