CREATE TABLE `yearly_aid_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`donorId` varchar(100) NOT NULL,
	`donorName` varchar(255) NOT NULL,
	`donorType` enum('un_agency','bilateral','multilateral','ngo'),
	`totalFunding` bigint,
	`fundingRequested` bigint,
	`fundingGap` bigint,
	`fundingPercentage` varchar(20),
	`totalBeneficiaries` int,
	`childrenBeneficiaries` int,
	`womenBeneficiaries` int,
	`foodSecurity` bigint,
	`health` bigint,
	`wash` bigint,
	`education` bigint,
	`protection` bigint,
	`shelter` bigint,
	`nutrition` bigint,
	`logistics` bigint,
	`other` bigint,
	`projects` int,
	`partners` int,
	`governoratesCovered` int,
	`dataQuality` enum('high','medium','low'),
	`notes` text,
	`sources` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `yearly_aid_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `yearly_bank_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`bankId` varchar(100) NOT NULL,
	`bankName` varchar(255) NOT NULL,
	`bankType` enum('commercial','islamic','microfinance','central'),
	`totalAssets` bigint,
	`totalDeposits` bigint,
	`totalLoans` bigint,
	`nplAmount` bigint,
	`nplRatio` varchar(20),
	`nplProvision` bigint,
	`capitalAdequacyRatio` varchar(20),
	`liquidityRatio` varchar(20),
	`netIncome` bigint,
	`returnOnAssets` varchar(20),
	`returnOnEquity` varchar(20),
	`branches` int,
	`employees` int,
	`customers` int,
	`activeBorrowers` int,
	`grossLoanPortfolio` bigint,
	`auditFirm` varchar(255),
	`auditDate` varchar(10),
	`dataQuality` enum('high','medium','low'),
	`notes` text,
	`sources` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `yearly_bank_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `yearly_conflict_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`totalFatalities` int,
	`civilianFatalities` int,
	`combatantFatalities` int,
	`totalInjuries` int,
	`childDeaths` int,
	`newIdps` int,
	`totalIdps` int,
	`returnees` int,
	`healthFacilitiesDamaged` int,
	`schoolsDamaged` int,
	`waterSystemsDamaged` int,
	`dataQuality` enum('high','medium','low'),
	`notes` text,
	`sources` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `yearly_conflict_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `yearly_conflict_data_year_unique` UNIQUE(`year`)
);
--> statement-breakpoint
CREATE TABLE `yearly_macro_indicators` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`gdpCurrentUsd` bigint,
	`gdpGrowthRate` varchar(20),
	`gdpPerCapita` bigint,
	`inflationRate` varchar(20),
	`exchangeRateOfficial` varchar(20),
	`exchangeRateParallel` varchar(20),
	`exports` bigint,
	`imports` bigint,
	`tradeBalance` bigint,
	`foreignReserves` bigint,
	`externalDebt` bigint,
	`population` bigint,
	`idps` int,
	`refugees` int,
	`foodInsecure` int,
	`dataQuality` enum('high','medium','low'),
	`notes` text,
	`sources` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `yearly_macro_indicators_id` PRIMARY KEY(`id`),
	CONSTRAINT `yearly_macro_indicators_year_unique` UNIQUE(`year`)
);
--> statement-breakpoint
CREATE TABLE `yearly_remittance_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`totalRemittances` bigint,
	`remittanceOperations` int,
	`moneyExchangers` int,
	`licensedCompanies` int,
	`dataQuality` enum('high','medium','low'),
	`notes` text,
	`sources` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `yearly_remittance_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `yearly_remittance_data_year_unique` UNIQUE(`year`)
);
