CREATE TABLE `actor_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorId` varchar(100) NOT NULL,
	`actorName` varchar(255) NOT NULL,
	`actorType` enum('central_bank','government','de_facto_authority','armed_group','foreign_government','multilateral','ngo','bank','mfi','commercial') NOT NULL,
	`actionDate` timestamp NOT NULL,
	`actionType` varchar(100) NOT NULL,
	`actionTitle` varchar(255) NOT NULL,
	`actionDescription` text NOT NULL,
	`impactDirection` enum('stabilizing','destabilizing','redistributive','extractive','neutral','mixed') NOT NULL,
	`timeHorizon` enum('immediate','short_term','medium_term','long_term','structural') NOT NULL,
	`affectedIndicators` json NOT NULL,
	`linkedEventIds` json,
	`sources` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `actor_actions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `actor_impact_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorId` varchar(100) NOT NULL,
	`actorName` varchar(255) NOT NULL,
	`startYear` int NOT NULL,
	`endYear` int NOT NULL,
	`macroStabilityScore` decimal(5,2),
	`volatilityChange` decimal(10,2),
	`macroStabilityEvidence` json NOT NULL,
	`distributionalScore` decimal(5,2),
	`poorHouseholdsImpact` text,
	`richHouseholdsImpact` text,
	`distributionalEvidence` json NOT NULL,
	`institutionalScore` decimal(5,2),
	`institutionalStrengthening` text,
	`institutionalWeakening` text,
	`institutionalEvidence` json NOT NULL,
	`overallAssessment` text NOT NULL,
	`keyFindings` json NOT NULL,
	`assessmentConfidence` enum('low','medium','high') NOT NULL,
	`dataSeriesUsed` json NOT NULL,
	`reportsUsed` json NOT NULL,
	`lastUpdated` timestamp NOT NULL DEFAULT (now()),
	`analystNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `actor_impact_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `actor_impact_profiles_actorId_unique` UNIQUE(`actorId`)
);
--> statement-breakpoint
CREATE TABLE `data_conflicts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`indicatorId` varchar(100) NOT NULL,
	`indicatorName` varchar(255) NOT NULL,
	`year` int NOT NULL,
	`primaryValue` decimal(20,2) NOT NULL,
	`primarySource` varchar(255) NOT NULL,
	`primarySourceId` varchar(100) NOT NULL,
	`alternativeValue` decimal(20,2) NOT NULL,
	`alternativeSource` varchar(255) NOT NULL,
	`alternativeSourceId` varchar(100) NOT NULL,
	`discrepancyPercent` decimal(10,2) NOT NULL,
	`conflictSeverity` enum('minor','moderate','major','critical') NOT NULL,
	`methodologicalDifference` text,
	`coverageDifference` text,
	`timingDifference` text,
	`resolutionMethod` text NOT NULL,
	`primarySeriesRationale` text NOT NULL,
	`alternativeSeriesAvailable` int NOT NULL DEFAULT 1,
	`additionalSources` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_conflicts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_revision_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('indicator','event','actor','narrative','source') NOT NULL,
	`entityId` varchar(100) NOT NULL,
	`entityName` varchar(255) NOT NULL,
	`year` int,
	`changeType` enum('created','updated_value','updated_source','updated_methodology','updated_narrative','corrected_error','added_alternative_series','deleted') NOT NULL,
	`previousValue` text,
	`newValue` text,
	`changeReason` text NOT NULL,
	`triggerEvent` varchar(255),
	`sourceUpdate` varchar(255),
	`changedBy` varchar(255) NOT NULL,
	`reviewedBy` varchar(255),
	`supportingDocuments` json,
	`relatedRevisions` json,
	`changeTimestamp` timestamp NOT NULL DEFAULT (now()),
	`publiclyVisible` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_revision_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `source_bias_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceId` varchar(100) NOT NULL,
	`sourceName` varchar(255) NOT NULL,
	`primaryBias` varchar(100) NOT NULL,
	`biasDescription` text NOT NULL,
	`fundingSource` text,
	`politicalAffiliation` varchar(255),
	`economicInterests` text,
	`narrativeTendency` text NOT NULL,
	`typicalFraming` text,
	`blindSpots` text,
	`strengths` text NOT NULL,
	`bestUsedFor` text,
	`exampleBias` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `source_bias_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `source_confidence_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceId` varchar(100) NOT NULL,
	`sourceName` varchar(255) NOT NULL,
	`sourceType` enum('multilateral','government','de_facto_authority','think_tank','ngo','media','academic','commercial') NOT NULL,
	`timelinessScore` int NOT NULL,
	`transparencyScore` int NOT NULL,
	`methodologyScore` int NOT NULL,
	`independenceScore` int NOT NULL,
	`consistencyScore` int NOT NULL,
	`overallConfidence` decimal(5,2) NOT NULL,
	`confidenceLevel` enum('low','medium','high','very_high') NOT NULL,
	`lastReviewed` timestamp NOT NULL DEFAULT (now()),
	`reviewedBy` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `source_confidence_scores_id` PRIMARY KEY(`id`)
);
